/*
 * EventDisplayComponent.java
 *
 * Displays the properties of an event.
 *
 * Created on Feb 28, 2009, 7:10:42 PM by Carey Zhang
 */

package zcalendar;

import javax.swing.text.Highlighter;

/**
 *
 * @author Owner
 */
public class EventDisplayComponent extends javax.swing.JPanel
{
    private Event event;        // Event currently displayed

    /** Creates new form EventDisplayComponent */
    public EventDisplayComponent()
    {
        initComponents();
        update();
    }

    /**
     * Sets the event being displayed and updates GUI.
     */
    public void setEvent(Event e)
    {
        // already same, do nothing
        if (event == e)
            return;

        event = e;
        update();
    }

    /**
     * Updates the GUI to match the current event.
     */
    public void update()
    {
        if (event != null)
            eventDisplay.setText(event.toString());
        else
            eventDisplay.setText(
                    "Name: " + "\n" +
                    "Date: " + "\n" +
                    "Description: ");
    }

    /**GUI CODE**/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eventDisplay = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        eventDisplay.setBackground(new java.awt.Color(240, 240, 240));
        eventDisplay.setColumns(20);
        eventDisplay.setEditable(false);
        eventDisplay.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        eventDisplay.setLineWrap(true);
        eventDisplay.setRows(5);
        jScrollPane1.setViewportView(eventDisplay);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea eventDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
